### ISSUE TITLE
Chpter 5: Multiple view geometry code?

### ISSUE THREAD

**Issue by Ezekiel-Kruglick** [jesolem/PCV#17]
Hi Jan-

Any chance you could post the code from chapter 5? I wanted to mess around with the plane_sweep stuff (stereo.py) and right now it looks like that would require typing in the code manually from the book?

-darkgreen

**Comment by nico** [comment]
(In the meantime, you can get a copy from https://github.com/nico/cvbook/blob/master/stereo.py)

**Comment by Ezekiel-Kruglick** [comment]
Thanks!
