### ISSUE TITLE
Run SnapSudoku on a smart phone?

### ISSUE THREAD

**Issue by cclauss** [jesolem/PCV#25]
https://github.com/prajwalkr/SnapSudoku/issues/3

It would be cool to get [SnapSudoku running on the iPhone](https://forum.omz-software.com/topic/3050/snapsudoku) so that you could use the camera to do the snap and immediately solve the puzzle right on the phone.  _It would drive Sudoku players crazy if you could walk up with your smart phone, snap a picture of their puzzle, and show them the solution._  [Pythonista](http://omz-software.com/pythonista) is a Python 2.7 and 3.5 IDE for iOS.  Pythonista does support NumPy, Matplotlib, and Pillow (PIL) but does **not** yet support OpenCV or SciPy.

@jesolem @nico @The-Penultimate-Defenestrator

**Comment by nico** [comment]
wrong nico
