### ISSUE TITLE
Where can we find image files?

### ISSUE THREAD

**Issue by takeshi-a** [jesolem/PCV#26]
Dear Jan Erik Solem,

Many thanks for your book, "Programming Computer Vision with Python."
I'm learning how to process computer images by your book.

Although there are many image files used in the sample programs, I could not find them in this repository. Some files have path like 'data/image.png', but I could not find such folder.

We can find several reference sites for us to collect image files in your book. But do we have to pick up each image file to trace your sample codes?

I'll be happy if I could have a good way to gather the image files.
Thanks.

Best,
Takeshi Akutsu (@akucchan_world)

**Comment by takeshi-a** [comment]
Sorry. I've just realized that we can download the zipped file of images on your website here.
[http://programmingcomputervision.com/](http://programmingcomputervision.com/)

I missed to check the shell file, "get-data-files.sh" on the top folder which downloads the data files. Please let me dismiss the question above.

**Comment by jesolem** [comment]
Great. Closing then.

**Comment by takeshi-a** [comment]
Thanks for your kind follow-up. As I posted a tweet on your account, I am organizing a Python learning community, "Start Python Club", in Tokyo. There are over 1,000 members in our club.
[http://startpython.connpass.com/](http://startpython.connpass.com/)

I introduced your book at our monthly meet-up yesterday, and had a lot of attentions from attendees. I would like to keep learning on your book. If I found some troubles again, please let me ask you. I appreciate your great work.
