### ISSUE TITLE
minor error in morphology.py

### ISSUE THREAD

**Issue by rsignell-usgs** [jesolem/PCV#4]
There is a minor error in morphology.py, reported here:
http://oreilly.com/catalog/errataunconfirmed.csp?isbn=0636920022923

In the above post, the reporter fixed the problem by replacing the original line

```
 im = 1*(im<128)
```

with 

```
 im = (im<128)
```

while I fixed the problem by replacing the line with

```
 im = 1.0*(im<128)
```

not sure which is more appropriate/robust.

-Rich Signell

**Comment by jesolem** [comment]
They all give the same result for me. Changed it to the second option just in case.
